# Generated by Django 4.2 on 2025-10-19 12:45

from django.db import migrations, models
import uuid


def generate_unique_share_links(apps, schema_editor):
    """Generate unique UUID for each existing project"""
    Project = apps.get_model('accounts', 'Project')
    for project in Project.objects.all():
        project.share_link = uuid.uuid4()
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_security_answer_user_security_question'),
    ]

    operations = [
        # Step 1: Add field as nullable without unique constraint
        migrations.AddField(
            model_name='project',
            name='share_link',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        # Step 2: Populate unique UUIDs for existing projects
        migrations.RunPython(generate_unique_share_links, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='project',
            name='share_link',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
