# Generated by Django 4.2 on 2025-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='version_file',
            field=models.FileField(blank=True, null=True, upload_to='project_versions/'),
        ),
        migrations.AlterUniqueTogether(
            name='projectversion',
            unique_together={('project', 'version_number')},
        ),
    ]
