# Generated by Django 4.2 on 2025-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_project_share_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectversion',
            name='action',
            field=models.CharField(choices=[('created', 'Project Created'), ('file_added', 'File Added'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('shared', 'Project Shared'), ('comment_added', 'Comment Added'), ('manual', 'Manual Save')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='projectversion',
            name='files_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterUniqueTogether(
            name='projectversion',
            unique_together={('project', 'version_number')},
        ),
    ]
