# Generated by Django 4.2 on 2025-10-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_projectversion_action_projectversion_files_snapshot_and_more'),
        ('accounts', '0005_projectversion_file_size_projectversion_file_type_and_more'),
    ]

    operations = [
    ]
