# Generated by Django 4.2 on 2025-10-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20251027_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_collaborators_delete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectversion',
            name='action',
            field=models.CharField(choices=[('created', 'Project Created'), ('file_added', 'File Added'), ('file_updated', 'File Updated'), ('file_deleted', 'File Deleted'), ('shared', 'Project Shared'), ('comment_added', 'Comment Added'), ('manual', 'Manual Save'), ('restored', 'Version Restored')], default='manual', max_length=20),
        ),
    ]
